#in eclipse 8091
#in local machine 8090
server.port = 8090

#config
app.config.comparator=json-comparator-service
app.config.keycloak=comparator-keycloak
app.config.keycloak=comparator-keycloak
#comparator.prop
#comparator.prop.config-section-name=comparator-manager
comparator.prop.env-enc-key=DEVKIT_KEY
comparator.prop.env-enc-iv=DEVKIT_IV
comparator.prop.env-config-path=DEVKIT_CONFIG_PATH
comparator.prop.web-client-memory-size=16777216




#swagguer
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none
#/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=false

#security and keycloak
server.ssl.enabled=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/comparator-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/comparator-realm/protocol/openid-connect/certs

# keycloak configuration
# the below is required 
keycloak.realm=comparator-realm
keycloak.auth-server-url=http://localhost:8080
keycloak.ssl-required=external
keycloak.resource=comparator-client
keycloak.credentials.secret=pMuvxG6YoLrfBFyq0FRsWQez7MwnihCc
keycloak.use-resource-role-mappings=true
keycloak.cors=false
keycloak.allow-any-hostname=true
#keycloak.bearer-only=true


# security log
logging.level.org.springframework.security=DEBUG